
amster:
  domain: .example.com

openam:
  domain: .example.com

openig:
  domain: .example.com

openidm:
  domain: .example.com

userstore:
  djInstance: userstore
  djPersistence: false
  opendjJavaArgs: "-Xmx400m"
  resources:
    limits:
      memory: 600Mi
    requests:
      memory: 400Mi

configstore:
  djInstance: configstore
  djPersistence: false
  opendjJavaArgs: "-Xmx400m"
  resources:
    limits:
      memory: 600Mi
    requests:
      memory: 400Mi