# Default values for dsadmin.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

component: ds

image:
  repository: gcr.io/engineering-devops
  pullPolicy: IfNotPresent
  tag: 6.5.0-M0

gcs:
  enabled: true
  # GCS Bucket destination. You need the right scopes in container engine to write to this bucket.
  #add --scopes storage-full when you create the cluster.
  bucket:  gs://forgeops/ds-backups
  
storage: {}

# If the pvc / pv already exists, use --set backup.createPVC=false
createPVC: true

backup:
  # The name of the PVC to create to hold backups from all ds instances.
  pvcName: ds-backup
  
  # If true this will mount a PVC of the given storage class on /opt/opendj/bak/
  enabled: false
  storageSize: "20Gi"
  # Backup schedule. The first backup is a full, subsequent backups are incremental
  # Format is crontab: minutes hour day-of-month month day-of-week
  schedule:  "*/60 * * * *"
  # If true, run a verification job
  verify: false
  
# For creating the PV, we need to speficy the server and the path to the export
nfs:
  server: 10.191.193.66
  path: /export

# An optional slack webhook url. It can be used by the backup and verification processes to post notifications to slack.
# If you don't have slack, set this to "undefined"
slackUrl: undefined