# Copyright (c) 2016-2017 ForgeRock AS. Use of this source code is subject to the
# Common Development and Distribution License (CDDL) that can be found in the LICENSE file
kind: Deployment
apiVersion: apps/v1beta1
metadata:
  # If you want to run more than one IG deployment in the same namespace, change the deployment name 
  # below to the {{ template "fullname" . }} to make the name unique.
  name:  {{ template "fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    vendor: forgerock
    component: {{ .Values.component }}
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "name" . }}
        release: {{ .Release.Name }}
        component: {{ .Values.component }}
        vendor: forgerock
    spec:
      {{ if eq .Values.config.strategy  "git" }}
      initContainers:
      - name: git-init
        image: forgerock/git:6.0.0
        #imagePullPolicy: {{ .Values.pullPolicy }}
        volumeMounts:
        - name: git
          mountPath: /git
        - name: git-secret
          mountPath: /etc/git-secret
        args: ["init"]
        envFrom:
        - configMapRef:
            name:  {{ default "frconfig" .Values.config.name  }}
      {{ end }}
      containers:
      - name: {{ .Chart.Name }}
        image: {{ template "image" . }}
        #imagePullPolicy: {{ .Values.pullPolicy }}
        env:
        - name: OPENIG_BASE
          value: "{{ .Values.config.path }}"
        - name: CATALINA_OPTS
          value: "{{ .Values.catalinaOpts }}"
        ports:
        - containerPort: {{ .Values.service.internalPort }}
        volumeMounts:
        {{ if eq .Values.config.strategy  "git" }}
        - name: git
          mountPath: /git
        {{ end }}
        livenessProbe:
          httpGet:
           path: /
           port: {{ .Values.service.internalPort }}
          timeoutSeconds: 10
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /
            port: {{ .Values.service.internalPort }}
          initialDelaySeconds: 5
        resources:
{{ toYaml .Values.resources | indent 12 }}
      volumes:
      {{ if eq .Values.config.strategy  "git" }}
      - name: git
        emptyDir: {}
      - name: git-secret
        secret:
          secretName:  {{ default "frconfig" .Values.config.name }}
      {{ end }}