# Default values for apache-agent.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1


service:
  name: nginx
  type: ClusterIP
  externalPort: 80
  internalPort: 80
resources:
  limits:
    cpu: 100m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 256Mi

# Default cookie domain. Include the leading dot.

global:
  domain: .example.com


component: nginx-agent

image:
  repository: forgerock
  tag: 6.0.1
  pullPolicy: IfNotPresent
